### ISSUE TITLE
Allow changelog to be provided as an input

### ISSUE THREAD

**Issue by arci** [rui-costa/action-automatic-semver-releases#4]
We are using [this](https://github.com/marketplace/actions/release-changelog-builder) action to generate the changelog in markdown, it would be nice if we can provide its output as in input to this one, something similar to this:

```yaml
name: "Release"

on:
  ...

jobs:
  release:
    name: "Release"
    runs-on: "ubuntu-latest"

    steps:
      ...

    - name: Build Changelog        
      id: build_changelog 
      uses: mikepenz/release-changelog-builder-action@v1        
      with:          
         ...

    - uses: "rui-costa/action-automatic-semver-releases@latest"
      with:
        ...
        generate_changelog: false # maybe this is redundant
        changelog:  ${{ steps.build_changelog.outputs.changelog }}
```
